// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuuwdpkaffwwywnfijxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1dXdkcGthZmZ3d3l3bmZpanh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODEyMTcsImV4cCI6MjA3MjE1NzIxN30.ta-lB74sDp67s6DAcj9pZmq63Azx_5uVvHyehzj5vg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});